### ISSUE TITLE
It fails on project start

### ISSUE THREAD

**Issue by ninedev-i** [Chris2011/nuxt-asciidoc#5]
> ERROR  [worker reload] [worker init] Cannot find module 'C:\nuxt-asciidoc@1.0.0\node_modules\nuxt-asciidoc\dist\runtime\plugin.ts'

**System**: windows

**package.json:**
```
{
  "dependencies": {
    "@nuxt/content": "2.12.1",
    "nuxt": "3.11.2",
    "vue": "3.4.27",
    "vue-router": "4.3.3"
  },
  "devDependencies": {
    "nuxt-asciidoc": "1.0.1"
  }
}
```
**nuxt.config.ts**
```
export default defineNuxtConfig({
  devtools: { enabled: false },
  modules: [
    'nuxt-asciidoc',
    '@nuxt/content'
  ]
})

```

**Comment by Chris2011** [comment]
The path seems weird to me: 'C:\nuxt-asciidoc@1.0.0\node_modules' or is 'C:\nuxt-asciidoc' just your project folder? Can you please add an sample archived project to this ticket here? Also please try to add 1.0.0 to devDependencies instead of 1.0.1.

**Comment by ninedev-i** [comment]
No, project folder is another: C\web\asciidoc.
And yes, I was trying to downgrade to 1.0.0 version, it wasn't successful.
Here is an sample project https://github.com/ninedev-i/nuxt-asciidoc-sample

**Comment by Chris2011** [comment]
hey @ninedev-i sry for the late delay, I will try to identify it in the next couple of days.

**Comment by Chris2011** [comment]
@ninedev-i please test the latest version 1.0.3. It worked now. The problem is smth with windows path. Depends on what I was using, it was relative or absolute, but absolute was C:/ but we need file:///. Maybe there is smth missing in the nuxt repo as well. Maybe @danielroe can also have a look before I create a PR for this. Maybe I was doing smth wrong.

**Comment by Chris2011** [comment]
I did a resaerch and found this: https://github.com/nuxt-themes/docus/issues/684 so my feeling is, that we need to update the nuxt module documentation and/or the nuxt-content documentation for creating a transformer.

**Comment by ninedev-i** [comment]
Problem is still there

**Comment by Chris2011** [comment]
can you please remove the .nuxt folder which is generated and also node_modules and the yarn.lock or package-lock.json if not done yet?

**Comment by ninedev-i** [comment]
> can you please remove the .nuxt folder which is generated and also node_modules and the yarn.lock or package-lock.json if not done yet?

I've done it before start

**Comment by Chris2011** [comment]
Ok thx, I will try it again. If you have a different setup now please share it with me. I will have a look again. Thx for testing.

**Comment by ninedev-i** [comment]
Same setup :)

**Comment by danielroe** [comment]
could you need to push something to `build.transpile`?

**Comment by Chris2011** [comment]
@ninedev-i so please use latest version 1.0.4 I missed to add the extension to the file, which I think is not needed but well. I cleaned everything now, maybe last time it was the cache that was correct...

@danielroe you mean to add my plugin name to the property? I tried it first but no difference, but I added some console.log into the plugin. I would like to have a talk sooner or later if possible when I create my second plugin to see whether I missed something when I go through the documentation of creating a nuxt module and the transformer for nuxt/content.

**Comment by ninedev-i** [comment]
@Chris2011 it works now, thx for your work!

**Comment by Chris2011** [comment]
Thx for your feedback. As @danielroe wrote here https://github.com/nuxt/nuxt/issues/13590#issuecomment-1397307722 and also as a comment in the plugin file, I should avoid adding the a filetype like *.ts to 'plugin'. But maybe I missed smth, because it never adds the correct filetype after build. So atm, I dunno whether I missed smth, which is quite possible :D, or the documentation has a gap or smth is weird on windows.
